<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="main.css"?>

<<<<<<< HEAD
<!DOCTYPE note [ 
<!ELEMENT note (title,university,plan,points)> 
<!ELEMENT title (#PCDATA)> 
<!ELEMENT university (#PCDATA)> 
<!ELEMENT plan (#PCDATA)> 
<!ELEMENT points (#PCDATA)>
]> 
=======
<specialization>
    <note>
        <title>Программное обеспечение информационных технологий</title>
        <university>БГУИР</university>
        <city>Минск</city>
        <plan>85</plan>
        <points>360</points>
    </note>
        <note>
        <title>Программное обеспечение информационных технологий (программирование Интернет-приложений)</title>
        <university>БГТУ</university>
        <city>Минск</city>
        <plan>40</plan>
        <points>330</points>
    </note>
        <note>
        <title>Программное обеспечение информационных технологий</title>
        <university>БНТУ</university>
        <city>Минск</city>
        <plan>30</plan>
        <points>340</points>
    </note>
>>>>>>> 1f5a43b8822d5b6a3bdbe46cdf812f9e17cce49c

<note>
    <title>Программное обеспечение информационных технологий</title>
    <university>БГУИР</university>
    <plan>85</plan>
    <points>360</points>
</note>

<note>
    <title>Программное обеспечение информационных технологий (программирование Интернет-приложений)</title>
    <university>БГТУ</university>
    <plan>40</plan>
    <points>330</points>
</note>

<note>
    <title>Программное обеспечение информационных технологий</title>
    <university>БГУИР</university>
    <plan>85</plan>
    <points>360</points>
</note>
